### ISSUE TITLE
Double input showing 

### ISSUE THREAD

**Issue by almogdesign** [aldeed/meteor-autoform-select2#13]
Getting a weird  UI issue attached screenshot 
![screen shot 2014-12-31 at 7 25 57 pm](https://cloud.githubusercontent.com/assets/169507/5589787/a49663d8-912f-11e4-89eb-5b5fc0edec10.png)

My code is pretty simple and based off the example 
```javascript
 {{> afQuickField name="producers" type="select2"}}
```
```javascript
producers: {
        type: [String],
        label: "Producers",
        optional: true,
        autoform: {
            type: "select2",
            options: function () {
                var user = Meteor.user();
                return Producers.find({organizationId: user.organizationId}).map(function (obj) {
                    return {label: obj.name, value: obj.name};
                });
            }
        }
    },
```

**Comment by aldeed** [comment]
You're using the shortcut `type: [String]` so it doesn't know whether you want the `autoform` stuff on the array or the array item. Try separating into `producers` and `'producers.$'`.

**Comment by almogdesign** [comment]
@aldeed thanks I should have closed this. I ended up having to build a custom form Autoform is great but my needs are very specific and custom which autoform can't do. I think it's good for the more general forms.
