### ISSUE TITLE
Loading 'AJAX' data

### ISSUE THREAD

**Issue by yogiben** [aldeed/meteor-autoform-select2#14]
I want to query a collection that's too big to publish / subscribe to. My initial thought is 

1) to use a method to achieve this
2) Setup a custom route that accepts a query

Have you any experience with this kind of problem?

**Comment by aldeed** [comment]
Yeah, usually I use some sort of typeahead input and call a server method in the ajax function for the typeahead. Select2 can do it, but you have to use a hidden input, which this package doesn't support. Otherwise I've used [Twitter typeahead](https://twitter.github.io/typeahead.js/) and [this one](http://autocompletejs.com/) in the past. It would be cool to have autoform custom input packages for some of these.

**Comment by gabrielhpugliese** [comment]
I'm doing a very ugly workaround:
```
            "countryId": {
              "type": Number,
              "label": "País",
              "autoform": {
                "type": "select",
                "options": function () {
                  Meteor.call('getCountries', function (err, res) {
                    if (! err && res && res.data) {
                      _.each(res.data, function (value, label) {
                        var $option = $('<option>').val(value).text(label);
                        $('select[name=countryId]').append($option);
                      });
                    }
                  });
                  return [];
                }
              }
            },
```

**Comment by abhishekbatra** [comment]
The dependence on hidden input fields has been removed in select2 4.0, but currently meteor-select2 package uses select2 3.5.1. Till that update happens, you can use [this](https://github.com/abhishekbatra/meteor-select2) temporary fork. Instructions on use are [here](http://zoomout-tv.blogspot.in/)

**Comment by aldeed** [comment]
v2 of this package is now released, which uses select2 4.0.

**Comment by abhishekbatra** [comment]
Hey @aldeed From what I see [here](https://github.com/nate-strauser/meteor-select2/blob/master/lib/select2/package.json) that package still uses 3.5.1

**Comment by abhishekbatra** [comment]
I stupidly missed [this](https://github.com/aldeed/meteor-autoform-select2#select2-library). Got it now, sorry and thanks :-)
