### ISSUE TITLE
Destroy

### ISSUE THREAD

**Issue by comerc** [aldeed/meteor-autoform-select2#17]
Why destroy-routines was deleted?

**Comment by aldeed** [comment]
I can't remember. I guess it could be added back.

**Comment by comerc** [comment]
```javascript
Template.afSelect2.destroyed = function () {
  this.$('select').select2('destroy');
};
```

**Comment by miri-am** [comment]
When removing from afEachArrayItem, this causes now: ```Exception from Tracker recompute function: Cannot read property 'destroy' of undefined TypeError: Cannot read property 'destroy' of undefined  at b.define.a.fn.select2.a.fn.select2 [as select2] ```

**Comment by metalik** [comment]
I have got the same exception as miri-am too
```
Exception from Tracker recompute function: Cannot read property 'destroy' of undefined
TypeError: Cannot read property 'destroy' of undefined
    at a.fn.select2.a.fn.select2 [as select2] (http://cdnjs.cloudflare.com/ajax/libs/select2/4.0.0-rc.1/js/select2.min.js:2:26761)
```
