### ISSUE TITLE
Select2 value not maintained when +/- buttons pressed in an array

### ISSUE THREAD

**Issue by markleiber** [aldeed/meteor-autoform-select2#18]
I'm not sure if I'm just doing something incorrectly, but when I use the select2 type in an array, the selected value disappears when I press the plus/minus (+/-) buttons.

I've created a reproduction of the issue here:
https://github.com/markleiber/autoform-select2-array-test

Other input types (normal selects, text fields, etc.) do not have this problem.

**Comment by markleiber** [comment]
I got this to work by adding this to autoform-select2.js on line 64 (before the _.each statement that pushes the options):
context.value = $("[name='" + context.atts.name + "']").val();

Not sure if this is the best approach or not.  I submitted a Pull Request.

**Comment by aldeed** [comment]
Thanks @markleiber. This is a tricky issue indeed. v2 of this package is now released, which uses select2 4.0 and has a workaround for this issue that is perhaps slightly less ugly than the one in your PR, though still pretty ugly. It seems to be mostly a quirk of how Blaze and Select2 interact when the DOM changes. Anyway, thanks for pointing this out.

**Comment by markleiber** [comment]
Thanks @aldeed, the update fixed the issue for me.  Much appreciated.
