### ISSUE TITLE
Tagging support for autoform-select2

### ISSUE THREAD

**Issue by chompomonim** [aldeed/meteor-autoform-select2#22]
Original select2 has `tags: true` option to get tagging possibility with it. Why we can't have same feature with autoform-select2?

What I would need it's 

```javascript
{
  typeTest: {
    type: [String],
    optional: true,
    autoform: {
      type: "select2",
      afFieldInput: {
        tags: true
      }
      options: function () {
        return [
          {label: "2013", value: 2013},
          {label: "2014", value: 2014},
          {label: "2015", value: 2015}
        ];
      }
    }
  }
}
```

It should autosuggest data from options and also allow to input any other string.

**Comment by aldeed** [comment]
I'll be updating this package to use select2 4.0, hopefully later today, and then you will be able to use tags. Prior to 4.0 a hidden input was required, so it didn't work with this package.

**Comment by aldeed** [comment]
v2 of this package is released, which uses select2 4.0 and tags will now work.

**Comment by chompomonim** [comment]
@aldeed Unfortunately it doesn't work with schema provided above. Should I add something additional?

**Comment by aldeed** [comment]
The `tags` option goes in the [select2 options](https://github.com/aldeed/meteor-autoform-select2#setting-select2-options). So it should work if you replace `tags` in your schema with `select2Options` set to the correct object.

**Comment by chompomonim** [comment]
Now it works while using select2Options. Thanks for pointing me to it.
