### ISSUE TITLE
Tags value is missing

### ISSUE THREAD

**Issue by Visudare** [aldeed/meteor-autoform-select2#26]
I have problems with the package. What I try to use is select2 with the options tags = true. This works as it should at the first look. I add tags and save it - after saving I checked the collection and the tags were added. But when display the update form the tags input field is always empty - the problem is that the tags will not be displayed in the value property (also when take a look into the dom the value is missing.)

This is my code:

In my Form "update" Template:

```html
{{> afQuickField name="tags" type="select2" multiple=true select2Options=s2Opts}}
```
My Template Helper:

```javascript
s2Opts: function () {
		return {placeholder: 'Tags', tags: true};
	}
```

In my Schema:

```javascript
tags: {
		type: [String],
		optional : true,
		autoform : {
			type : 'select2'
		}
	}
```

**Comment by Visudare** [comment]
It seems that the template is missing the selected="selected" option to work in the right way.

**Comment by niranjans** [comment]
@Visudare Hi, I have a similar problem. Did you just add `selected="selected"` and it worked? Or did you have to do something else. 

I have my SimpleSchema set like the following but it doesn't seem to work - 

```
    languages: {
    	type: [String],
    	optional: true,
        autoform: {
            type: "select2",
            options: function () {
                return [
                  {label: "Javascript", value: "Javascripts"},
                  {label: "Java", value: "Java"},
                  {label: "Ruby", value: "Ruby"},
                  {label: "Python", value: "Python"},
                  {label: "PHP", value: "PHP"},
                  {label: "Go", value: "Go"}
                ];
              },
            afFieldInput: {
                    multiple: true       
                }
        }
    }
```

**Comment by Visudare** [comment]
@niranjans I use now https://github.com/yogiben/meteor-autoform-tags/ instead of select2. This works perfectly and it seems that you can add typeahead and other stuff to this package (But I dont need this - just needed the tagging function)

**Comment by niranjans** [comment]
Oh ok. Thanks, I will check that out.

But I was also hoping to get select2 to work since I might be using that in other places too. Maybe @aldeed can help. 

I think its almost working. I have a single select with `select2` and that works perfectly and shows up the selected value when the update form is refreshed. However, it's just this multiselect input which saves the selected onces into the database but then shows blank when the autoform template refreshes.

**Comment by niranjans** [comment]
Some more info - This error started happening when my autoform package updated from 4.2.2 to 5.0.2 .
I just downgraded back to 4.2.2 and the select2 multi works as expected again.

**Comment by Visudare** [comment]
Nice to know @niranjans ! Hope this helps out to debug this problem :+1:

**Comment by rwatts3** [comment]
Any update on this I'm having the same issue.

**Comment by niranjans** [comment]
@rwatts3 I'm afraid I haven't found a solution. I did some trial and error but for now, I have set the autoform package version back to 4.2.2 to make it work. And I have been referring to the old docs from [here] (https://github.com/aldeed/meteor-autoform/blob/c9a42ee9818f877e41fc4290de8a31037fdeb780/README.md#objects-and-arrays) . 

However, this is obviously not ideal. I'm hoping @aldeed can give his input on this.

**Comment by aldeed** [comment]
Tested against 2.0.2 and this seems to work. The OP from @Visudare is missing the `options` attribute. Not exactly sure what's wrong with @niranjans code. If still having problems, please submit new issue with a link to a reproduction repo.

Note that this still does not work well with autosave in all cases. Planning some changes to the way we handle fields values and autosaving in core autoform, which should fix this.

**Comment by rwatts3** [comment]
@aldeed 
I'm not sure what you mean by missing options attribute.  It looks like options is in his code is there somewhere else it should be.  Could you copy his corrected code into a comment for reference. 

Also could you copy the example you used to test so I can reference could just be doing it the wrong way.

**Comment by aldeed** [comment]
It has `select2Options` but is missing `options`. Only options that are present can be selected.

Here's roughly my test edit form:

```html
{{> afQuickField name="tags" type="select2" multiple=true select2Options=s2Opts options=tagsOptions}}
```

Helpers:

```js
  s2Opts: function () {
    return {placeholder: 'optional', tags: true};
  },
  tagsOptions: function () {
    return _.map(this.tags || [], function (tag) {
      return {label: tag, value: tag};
    });
  }
```

In this case I'm just adding all the existing tags as options. So this would be a case where you're allowing any tags to be entered and stored, but you're not showing any additional preset list of tags. If you had a preset list, then tagsOptions would come from a Tags collection or something, but the idea is the same.

**Comment by niklasp** [comment]
can this also be set in the simpleschema?

**Comment by nikhildaga** [comment]
I am facing the same problem. tags are not saved. I get the error 

The select2('destroy') method was called on an element that is not using Select2.

My schema:
  
  causes: {
    type: [String],
    autoform: {
      type: 'select2',
      options: function() {
        return Causes.find().map(function(cause) {
          return {
            label: cause.title,
            value: cause._id
          }
        });
      },
      afFieldInput: {
        select2Options : {
          tags: true          
        }
      },
      multiple: true
    }
  }

**Comment by nikhildaga** [comment]
Ok. I understood the problem.  The reason we can't see new tags is because they are not in options. There should be a way to update options automatically. Or display tags other than options

**Comment by alexandrzavalii** [comment]
@nikhildaga I have the same problem, have you solved it?

**Comment by anthonyboutinov** [comment]
Is there any solution for this (apart from downgrading Autoform)?

**Comment by anthonyboutinov** [comment]
**BEST SOLUTION SO FAR**

I use `select2` as `npm` package, not this meteor wrapper that you are all using. So I have to write in the following manner:

```javascript
someFieldThatUsesSelect2: {
    type: [String],
    // ...
    autoform: {
      type: 'select-multiple',
      options: function() {/*...*/},
      //...
    },
  },
```
And then somewhere in code I run this:

```javascript
this.$('select').select2();
```

Remove select2 meteor wrapper and install select2 from npm. By using `'autoform.type': 'select-multiple'` instead of `'autoform.type': 'select2'`, the issue disappears.

I suppose, in Meteor Select2 wrapper for autoform, they use `select` input type template in both single- and multiple-selects.
