### ISSUE TITLE
what about autoform v5.0.2 ?

### ISSUE THREAD

**Issue by shkomg** [aldeed/meteor-autoform-select2#27]
Can't update autoform because

**Comment by aldeed** [comment]
It's compatible with autoform v5.0.2.

**Comment by shkomg** [comment]
thank you, but that's what I get

```
While selecting package versions:
error: conflict: constraint aldeed:autoform@4.0.7 is not satisfied by 5.0.2.
Constraints on aldeed:autoform come from:
<top level>                                                                                                                                                                               
aldeed:autoform-select2@2.0.1   
````

**Comment by aldeed** [comment]
That's some issue with the version resolver then because `aldeed:autoform-select2@2.0.1` has AF 5.0.0+ listed as dependency. What Meteor release?

**Comment by aldeed** [comment]
I was just able to reproduce by adding other packages that are not compatible with AF 5.0, but once those packages are removed it works fine. So it seems like the version resolver error message is just not very clear. Try removing any other packages with autoform dependencies and adding them back one by one, doing `meteor update` after each one.

**Comment by shkomg** [comment]
Cool, thank you.
I'm currently on Meteor 1.0.4.1

2015-03-19 17:23 GMT+02:00 Eric Dobbertin <notifications@github.com>:

> I was just able to reproduce by adding other packages that are not
> compatible with AF 5.0, but once those packages are removed it works fine.
> So it seems like the version resolver error message is just not very clear.
> Try removing any other packages with autoform dependencies and adding them
> back one by one, doing meteor update after each one.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aldeed/meteor-autoform-select2/issues/27#issuecomment-83628218>
> .
>



-- 
Best regards

Serhiy Khvashchuk
