### ISSUE TITLE
multiple option not working

### ISSUE THREAD

**Issue by fermuch** [aldeed/meteor-autoform-select2#29]
I've been trying to set a multiple input, but it doesn't seem to work anymore.

I created a meteor pad to show you the error, and in the pad it doesn't display the labels. I'm not sure why this is happening, but it doesn't happen to me. My problem is not being able to select more than one option.

http://meteorpad.com/pad/rqWMK6D6hfJiyxFX6/Leaderboard

My version of Meteor is 1.0.5, and the Meteor Pad is 1.0.2.1.

**Comment by aldeed** [comment]
Thanks. Merged PR which should fix this in 2.0.2.
