### ISSUE TITLE
Update form not displaying values for 'multiple=true' field

### ISSUE THREAD

**Issue by PauliBuccini** [aldeed/meteor-autoform-select2#3]
Hi,
Update form is not displaying values on select2 input with `multiple=true` option (same if defined in schema )

```
{{> afFieldInput name="cities" type="select2" multiple=true  options=citiesOptions}}
```
It updates the record, but once you open the update form again, the field is empty, even though values are set correctly in the database, i use `_id` for the `value` and `title` for `label`.

Here is a reproduction repo: https://github.com/PauliBuccini/autoForm-select2-test.git
Deployed: http://autoform-select2-test.meteor.com

**Comment by KMontag42** [comment]
siiiiiiiick

you guys rule!
