### ISSUE TITLE
Not clear selected value when change the options array?

### ISSUE THREAD

**Issue by yuomtheara** [aldeed/meteor-autoform-select2#31]
I have 2 select box:
- select1: ["A", "B"]
- select2: (empty)

1- When I change the `select1` to "A", I add new `options` to `select2` with ["X", "Y"] via session (It is work fine). And then I selected to "Y" on `select2`.

2- When I change the `select1` again to "B", I add new `options` to `select2` with the new ["V", "W"] via session too (It is work fine). But it still "Y" selected for the label on `select2` (value is empty), I think that `select2` should be " " selected.

**Comment by aldeed** [comment]
If this is not fixed with 2.0.2 version, please provide a link to a reproduction repo I can clone.

**Comment by yuomtheara** [comment]
Very thanks, now work fine.
