### ISSUE TITLE
Can't get value for default label with no (select one) on new version?

### ISSUE THREAD

**Issue by thearabbit** [aldeed/meteor-autoform-select2#33]
No default (select one) on the new version.
I have one select box that
- `Select1`: ["A", "B", "C"], so it will selected "A" for default of label and I set `Select1` is required
- When I click `submit` btn, it alert error `Select1 is required`, so it mean the `Select1` is null or empty but have the "A" label.

**Comment by yoh** [comment]
+1

**Comment by evallgar** [comment]
I'm having the same issue.

1- If Select2 options is only 1, submit will never return a value.
2- If Select2 options is greater than 1, but default selected value _is_ the value you need, you will have to select another value and _then_ select again the default value so this can _pass_ a value on submit.

Has anyone got an answer for this?

**Comment by aldeed** [comment]
Closing old issues (probably fixed).
