### ISSUE TITLE
afSelectOptionAtts helper missing?

### ISSUE THREAD

**Issue by Blood-dm** [aldeed/meteor-autoform-select2#34]
Hi,

I noticed that all my default option (options:) fields were missing the value attribute.

Schema:
```coffeescript
tags:
      type: [String]
      optional: true
      autoform:
        type: "select2"
        options: ->
           [{label: "test", value: "test"},{label: "test2", value: "test2"}]
        multiple: true
        select2Options:
          tags: true
          placeholder: "Add tags"
```
This is standing inside autoform-select2.html:
`<option {{afSelectOptionAtts}}>{{this.label}}</option>`

Fixed it by writing the deleted helper function again:
```javascript
Template.afSelect2.helpers({
  atts: function addFormControlAtts() {
    return _.omit(this.atts, 'select2Options');
  },
  afSelectOptionAtts: function afSelectOptionAtts() {
    var item = this;
    var atts = {
      value: item.value
    };
    if (item.selected) {
      atts.selected = "";
    }
    return atts;
  }
});
```

I don't know if this is a bug or a new 5.0 feature, but if anyone has the same problem they can use this quick fix.

**Comment by aldeed** [comment]
It is a global helper defined by autoform, since 5.0 I think. Yes, if you're not using 5.0 yet, you may need to define it yourself. Just copy [this](https://github.com/aldeed/meteor-autoform/blob/0df621c015528775a876f4a621bb6f92fbe345a5/autoform-helpers.js#L259-L271) into your app. Thanks.
