### ISSUE TITLE
"Insert" form carries over value from "update" form when reused, even when form is reset. 

### ISSUE THREAD

**Issue by bshamblen** [aldeed/meteor-autoform-select2#35]
Similar to the issue posted on the meteor-autoform project (https://github.com/aldeed/meteor-autoform/issues/751) when using the same form to perform both inserts and updates, by changing the `type` attribute of the form, the value that's displayed in a `select2` field will persist. However, unlike the other issue, executing `Autoform.resetForm(formId)` in the auto form `rendered` hook will not clear the value of a `select2` field like it does with all of the other fields. 

**Steps to reproduce**
1. Create an `#autoForm` with a `type` attribute that's set using a helper, returning `'insert'` or `'update'` based on the use case.
2. Add a `select2` property to the form.
3. Use the form to edit an existing document that has a value for the `select2` field.
4. Navigate away from the page.
5. Return to the page, this time using it as an `insert` form.
6. The previous value that was displayed from the edit form will still be displayed in the `select2` field, even though the `doc` is null.

As suggested in the meteor-autoform issue I added `Autoform.resetForm('myFormId')` to the Autoform template `rendered` hook. All of the other fields are cleared, as you would expect, but the `select2` field still shows the old value. 

_Note: If I change the field `type` to a standard `select` the value does not persist._

**Comment by andyxueyuan** [comment]
I have encounter the same issue. See my original post in Stackoverflow: http://stackoverflow.com/questions/30589320/how-to-reset-autoform-select2-input-box?noredirect=1#comment49268139_30589320 (and thanks @bshamblen for the answer)

Please find a solution for this. Appreciate it.

**Comment by thebarty** [comment]
Same problem here.

In my case I have a "resetForm" button and want to enable the user to reset the form values.
I am calling a ``Autoform.resetForm()`` which shall then reset the values, but select2 does NOT reset.

Did anyone find a workaround?
Is there a way to manually reset the select2 input?

**Comment by kuka** [comment]
Same thing.

Dirty temp solution is `` $('.select2-selection__choice__remove').click(); ``.

**Comment by Ragsboss** [comment]
+1 we are seeing this problem too :(

**Comment by thebarty** [comment]
damn I wish this bug had been fixed!!

@kuka: yeah this is a quick solution, but leads to buggy behaviour when reopening the select2 box... somehow internally the previous select-states are still saved

**Comment by thebarty** [comment]
Ok guys,

I spend two more hours on this and found a solution that works for me (thanks @kuka for this inspiration).

Have a template-helper like
```
globalSelect2Options() {
    return {
      allowClear: true,  // show extra clear button
    }
  }
```

Then assign this to the field within autoform like
```
{{> afQuickField name='topics' select2Options=globalSelect2Options }}
```

Then in your RESET-event do this:
```
$('.select2-selection__clear').mousedown()
```

Its a pity that autoform is dying: https://forums.meteor.com/t/autoform-is-dying/24361

**Comment by aldeed** [comment]
This is more of a fundamental issue with how autoform pkg does the reset. I don't see any clean solution to this, so I recommend clearing the value yourself as proposed in the workarounds.
