### ISSUE TITLE
Option 'tags' is not allowed for Select2 when attached to a <select> element.

### ISSUE THREAD

**Issue by samuelluis** [aldeed/meteor-autoform-select2#36]
Hello I have this field in my schema structure:

``` javascript
   tags: {
      type: [String],
      autoform: {
         type: "select2",
         afFieldInput: {
            multiple: true,
            select2Options: {
               tags: true
            }
         }
      }
   }
```

And I get this error:

```
Error: Option 'tags' is not allowed for Select2 when attached to a <select> element.
    at String.<anonymous> (select2.js:928)
    at Function.jQuery.extend.each (jquery.js:384)
    at clazz.prepareOpts (select2.js:926)
    at clazz.prepareOpts (select2.js:2584)
    at clazz.init (select2.js:693)
    at HTMLSelectElement.<anonymous> (select2.js:3375)
    at Function.jQuery.extend.each (jquery.js:384)
    at jQuery.fn.jQuery.each (jquery.js:136)
    at $.fn.select2 (select2.js:3362)
    at Template.afSelect2.rendered (autoform-select2.js:126)
```

Please tell me if you know how to fix it. Thanks.

**Comment by masca88** [comment]
+1

**Comment by nikhildaga** [comment]
I am facing the same problem

**Comment by jmurty** [comment]
For Select2 versions before 4, the "tags" option can only be attached to a text input field. Version 4 does allow this usage. See http://stackoverflow.com/questions/24146954/jquery-select2-breaks-as-soon-as-i-add-tags

I just hit this problem myself. Thought I might as well clarify things here.

**Comment by threefoldo** [comment]
Using select2 v4.0+ will solve the problem. The "README" said this specifically.

**Comment by suraj04081993** [comment]
Refer this link for more information - http://itfrustration.in/jquery-select2-ajax/

**Comment by FrederickChan** [comment]
@suraj04081993 - Link's dead.
