### ISSUE TITLE
Problem with select2 when using in array of object fields? 

### ISSUE THREAD

**Issue by thearabbit** [aldeed/meteor-autoform-select2#38]
I use select2 filed in array of object in schema.
When I click add more (+), It clear all of selected value at the top.
Please help me.

**Comment by alexandrzavalii** [comment]
@thearabbit I have the same problem.
Have you solved this?

**Comment by alexandrzavalii** [comment]
@thearabbit I updated select2.min.css and min.js  to the version 4.0.3 and it worked.

**Comment by thearabbit** [comment]
Look great, Could provide the link repo for example?

**Comment by artjomg** [comment]
I still have this issue and would appreciate any hint how to fix this the js and css file I am using are 4.0.3. It looks to me like autoform array handling ist not comaptible with select2.
Thx
