### ISSUE TITLE
Optgroup support

### ISSUE THREAD

**Issue by atoi** [aldeed/meteor-autoform-select2#4]
Hi,
autoform-select2 does not work correctly when you set up optgroups in your options helper.
Judging from the code I can tell that the case is that it expects plain array of items to be transformed into select options.
Is there a way of defining option groups or that feature is officially not supported?

**Comment by stlouisweb** [comment]
I just submitted a pull request that copies over the optgroup code from the autoform base package.

**Comment by aldeed** [comment]
Closing. Merged PR and will release soon.
