### ISSUE TITLE
PlaceHolder with singleOption

### ISSUE THREAD

**Issue by fipke** [aldeed/meteor-autoform-select2#40]
Hello, Sorry, I'm starting with meteorjs, and I cannot add a placeholder to my single-selection , I don't know if I'm doing something wrong or is there a limitation with single selection

when I do so, it works, but I want only single selection

```
afFieldInput:{
            multiple:true,
            placeholder: 'Test1'
      },
```

but when I remove the "multiple:true" the placeholder disappears, and is showed the first option '2013'

```
typeTest: {
    type: String,
    optional: false,
    allowedValues: [ '2013','2014','2015'],
    autoform: {
      type: "select2",
      afFieldInput:{
            multiple:false,
            placeholder: 'Test1'
      },
      options: function () {
        return [
          {label: "2013", value: '2013'},
          {label: "2014", value: '2014'},
          {label: "2015", value: '2015'}
        ];
      }
    }
  }
```

```
{{> afQuickField name='typeTest'}}
```

Am I doing something wrong?
Thank you

**Comment by chiester** [comment]
Try removing the "multiple" property altogether.

**Comment by panayi** [comment]
Seems this is a bug - see this SO answer: http://stackoverflow.com/a/21414098/359104. I think `contextAdjust` should prepend an empty `<option></option>` when `multiple=true` and `placeholder` is passed.

**Comment by panayi** [comment]
The above is also mentioned in select2 docs: https://select2.github.io/options.html#placeholder
