### ISSUE TITLE
autoValue & defaultValue not working.

### ISSUE THREAD

**Issue by rwatts3** [aldeed/meteor-autoform-select2#41]
Greetings, 

I've tried different approaches to try and use autoValue and defaultValue with no success. 
I have a forum that will attach a post, and the post collection contains a relationship that looks for forumId. I tried to pass the forumId, using autoValue, however the entry still submits without the value of the the forumID. I even attempted to hardcode the value so that any post will automatically use the hardcoded value, and still no luck. 

Any advice ? 

Thank you , 

Ryan

**Comment by gabdsg** [comment]
I have the same problem

**Comment by aldeed** [comment]
Closing old issues. This seems like it would be an issue with autoform pkg
