### ISSUE TITLE
How to set selected value  

### ISSUE THREAD

**Issue by AlmogRnD** [aldeed/meteor-autoform-select2#43]
How can set the selected value if there is one in the auto form scheme 

Currently trying the following but then I can't see the rest of the countries list 

``` javascript
options: function () {
                var user = Meteor.users.findOne();
                if (user && !_.isEmpty(user.profile.country)) {
                    return {value: user.profile.country};
                }
                return countriesList;
            }
```

**Comment by thearabbit** [comment]
You solve this?
Pleas share me.

**Comment by raphaelarias** [comment]
Any news on this? :)

**Comment by raphaelarias** [comment]
I'll test, but maybe this works: http://stackoverflow.com/questions/29443084/how-can-i-pre-select-a-value-from-a-dropdown-list-with-meteor-and-autoform

firstOption=

https://github.com/aldeed/meteor-autoform#affieldinput

**Comment by gabdsg** [comment]
You solve this?

**Comment by raphaelarias** [comment]
Return the options object with the keys label and value.

Add the doc param to Autoform helper and in this doc you should have a key that matches your input with the value you want. Autoform will auatomatically display the value of it is in the options.
