### ISSUE TITLE
Select 2 --- Width of Field in Form (Using Modal)

### ISSUE THREAD

**Issue by frank1340** [aldeed/meteor-autoform-select2#49]
```
specialty: {
    type: [String],
    minCount: 1,
    autoform:{
        type:'select2',
        multiple: true,
        options:function() {
            return specialties.find().map(function(s) {
                return {label: s.name, value:s.name};
            })
        }
    }
},
```

Yields

![image](https://cloud.githubusercontent.com/assets/6349740/10433642/8ee68e22-70e1-11e5-92cc-5bd6d1d70b8e.png)

What am I doing wrong here?  Thank you.

**Comment by bipin244** [comment]
In css give this i think it is usefull:
.select2-container.form-control {
	width: 23%;
	height:50px;
}

**Comment by Framnk** [comment]
I'm having the same issue and the suggested CSS fix doesn't appear to resolve the problem.  Any help is appreciated

**Comment by luixal** [comment]
Problem is that the rendered html tag contains a custom style (style="width: 100px;"). I've tried to add a custom CSS to set width to 100% (which looks fine), but width gets always overriden by the value included in the tag.

Any idea on how to avoid this? It's kind of un-usable for me as it looks now.

**Comment by luixal** [comment]
FYI: for the moment, I've moved to [autoform-selectize](https://atmospherejs.com/comerc/autoform-selectize). It renders at full width by default and usage is the same. Just needed to change the type field from "select2" to "selectize".

**Comment by aldeed** [comment]
Closing old issues

**Comment by AdrianAbba** [comment]
same problem and cant find any old issue for a solution :/
