### ISSUE TITLE
Remove the 'firstOption' when using Select2

### ISSUE THREAD

**Issue by cyrus-za** [aldeed/meteor-autoform-select2#5]
Not sure if this should rather go into StackOverflow, but I started using select2 in my autoform for meteor-admin and it seems to have the firstOption defaulting to "(Select One)", which makes sense for a normal Select, but in Select2, that is now in the array of valid options. 

# EDIT:
I tried making the value a empty string, null or undefined and it didn't do anything. Then after scanning through the code in the repository I saw there's a 

    if (firstOption !== false)

so I switched my firstOption to false and it magically disappeared. Maybe just put it in the readme/documentation.

**Comment by sylido** [comment]
Yeah, this was confusing.

**Comment by aldeed** [comment]
Agree, it probably makes sense to skip the firstOption stuff in this package.
