### ISSUE TITLE
Do not set "selected" from the database.

### ISSUE THREAD

**Issue by ivansglazunov** [aldeed/meteor-autoform-select2#50]
``` html
{{#autoForm collection="Parents" id="autoFormParent" type="update" doc=doc}}
    {{> afQuickField name='elements' select2Options=select2Options}}
{{/autoForm}}
```

``` js
ParentsSchema = new SimpleSchema({
    elements: {
        type: [String],
        defaultValue: [],
        autoform: {
            type: "select2",
            afFieldInput: {
                multiple: true
            }
        }
    }
});
```

``` js
Template.autoFormParent.helpers({
    select2Options: function() {
        return {
            data: lodash.map(Elements.find().fetch(), function(element) {
                return { id: element._id, text: element.name, selected: true };
            })
        };
    }
});
```

The list of options is displayed. Already set the tags are not displayed.
The database changes are saved.
Where is my mistake? Or is it a bug?

**Comment by efuturetoday** [comment]
same here - how to fix it? 
I noticed that the original select-ultiple dosent work too with autoform 5.7.1
<code>
  label: "Majors",
    type: [String],
    optional: true,
    allowedValues: ['Physics', 'Math', 'Biology', 'Chemistry'],
    autoform: {

      type: 'select-multiple',
  afFieldInput: {
            multiple: true
        }
    }
  }
</code>

**Comment by timjong93** [comment]
If anyone still has this problem, updating to the 4.0.3 release of select2 fixed this problem for me.

**Comment by Sojourneer** [comment]
Updating to 4.0.3 doesn't solve the problem.
Setting type="select" and calling elt.select2(options) in the onRender() handler does work.
