### ISSUE TITLE
OptGroup Example

### ISSUE THREAD

**Issue by BrianSHenderson** [aldeed/meteor-autoform-select2#51]
I'm struggling with entering the options with optgroup information in the correct format, is there an example to enter into the SimpleSchema?

Thanks

**Comment by JonniK** [comment]
faced this problem too. did you find a desision?

**Comment by BrianSHenderson** [comment]
Sorry I avoided using it in the end

**Comment by JonniK** [comment]
in last version all works great!

**Comment by abate** [comment]
A small example would be useful anyway ... @JonniK ?

**Comment by aldeed** [comment]
Yes @abate, normal optgroup like that should work.
