### ISSUE TITLE
Removing one item from Array type, results in empty item not deletion.

### ISSUE THREAD

**Issue by keyscores** [aldeed/meteor-autoform-select2#56]
Only the last item in an array form can successfully be removed. Any item from 0 to -1 will not be removed completely, and will only be blank. 

See repo to reproduce: https://github.com/keyscores/meteorautoformissue
and hosted here: http://afarrayselectissue.meteor.com/

In this example there are 2 items in an array.
If you click ' - ' to remove the item ' Project - A ' and then submit, you will have an empty array item. The desired result would be to have no item at all.

**Comment by Sojourneer** [comment]
I have the same problem.
The workaround I used is to _.compact(modifier.$set.<field>) in the AutoForm hook formToModifier

**Comment by aldeed** [comment]
Pretty sure this would be autoform pkg issue and not this package
