### ISSUE TITLE
aria-selected value is set to "true" before clicking on any options of select2

### ISSUE THREAD

**Issue by devarashetty** [aldeed/meteor-autoform-select2#59]
//this is similar example to mine
'checking': {
      type: String,
      label: "checking variable",
      optional: true,
      autoform: {
        type: "selectize",
        options: function() {
          return Meteor.users.find({
            }).map(function(u) {
            return {
              label: u.FullName(),
              value: u._id
            };
          });
        }
      }
    }

**Comment by aldeed** [comment]
Closing old issues. This is most likely a select2 package issue.
