### ISSUE TITLE
Does select2 require an Autoform 

### ISSUE THREAD

**Issue by elewis33** [aldeed/meteor-autoform-select2#60]
This is probably a really dumb question, I know, but do you need to have an Autoform implemented for the select2 package to work? The example on the README makes it look like you can do a select2 without an Autoform, but is it assuming that there's an Autoform where you place the select2?

I have all of the packages added to my meteor project (autoform, autoform-select2 and the bootstrap css), but I wanted to know if I could implement the select2 without an autoform.

**Comment by rhlsthrm** [comment]
select2 is a DOM element, so you should be able to use it without AutoForm no problem.

**Comment by aldeed** [comment]
As long as you use it according to their docs rather than as described in this repo, it will work outside of autoform. https://select2.github.io/
