### ISSUE TITLE
Update template-extension from 3.4.3 to 4.0.0

### ISSUE THREAD

**Issue by Ragsboss** [aldeed/meteor-autoform-select2#62]
Unless there is a reason, could we please update the dependency template-extension to its latest available version 4.0.0?

**Comment by h4de5** [comment]
just tried to update an app, and got this:
 
> aldeed:autoform-select2*    downgraded from 2.0.2 to 1.0.5
> aldeed:template-extension*  upgraded from 3.4.3 to 4.0.0

and the select2 fields are no longer working. is there a way where i can install all current values?

**Comment by aldeed** [comment]
Fixed in next release
