### ISSUE TITLE
Select2 fields visually clear when subscription update

### ISSUE THREAD

**Issue by CharlesNo** [aldeed/meteor-autoform-select2#63]
Hi,

So I use select2 fields on a form to create Jobs. One of these fields require the user to select a Company (another collection). The problem is when someone is creating a job and someone else is creating a new Company, the select2 fields fro the first guy are updated and go blank.

Do I did something wrong with the package?
Everything is setup on a SimpleSchema like this :

`company: {
    type: String,
    optional: true,
    defaultValue: null,
    label: 'Company',
    autoform: {
      type: "select2",
      options: function() {
        return Companies.find({}, {
          sort: [["name", "asc"]]
        }).fetch().map(function(d) {
          return {
            label: d.name,
            value: d._id
          };
        });
      }
    }
  }`

**Comment by jkd65** [comment]
Having this same issue

**Comment by aldeed** [comment]
If you don't want this to happen, best solution is probably to pass `{ reactive: false }` option to `find`
