### ISSUE TITLE
Tags in Update Form

### ISSUE THREAD

**Issue by neil-s** [aldeed/meteor-autoform-select2#64]
My use case is this: I have an update quickform, with a field called 'markets', that accepts a `[String]`. I would like to enable tags support on it. Hence, it should do 3 things:
a) show the markets the doc previously contained
b) let the user choose one of the suggestions for additional markets to add to the array
c) let the user create a new market to add to the array

Could the README please be updated to include a tags example that does this, especially (a).

I have spent hours trying to debug this, walking through the code, but somehow I just can't get the current values from the doc to show up as already selected. My schema:

```
    markets: {
        type: [String],
        autoform: {
            type: "select2",
            afFieldInput: {
                multiple: true,
                select2Options: {
                    data: [
                        {id: "Education", text: "Education"},
                        {id: "Financial Services", text: "Financial Services"},
                        {id: "Healthcare", text: "Healthcare"}
                    ],
                    tags: true
                }
            }
        },
    },
```

The doc currently has Financial Services and Healthcare chosen, so those two tags should appear in the tag box already. However, the box appears empty, with the three options listed above.

I'm using the following relevant package versions:

```
natestrauser:select2@4.0.1
aldeed:autoform@5.8.1
aldeed:autoform-select2@2.0.2
yogiben:admin@1.2.4
```

**Comment by threefoldo** [comment]
I hit the same problem. There is a method to manually add tags, but that's not a solution:
$("#myselect").val("select-option").trigger('change')

**Comment by threefoldo** [comment]
No, that's not working. Putting select2 options in SimpleSchema can solve the problem.

**Comment by dpeet** [comment]
@threefoldo do you have an example of that working? Or are you saying that Aldeed needs to add it for it to work?

**Comment by alexandrzavalii** [comment]
@dpeet Is the issue solved? 
I have to define tags:true in the SimpleSchema. 
Does anyone know how to do this?

**Comment by dpeet** [comment]
@alexandrzavalii I seem to have it working for now.  One of my issues was that one of my collections wasn't filling properly, so I checked to make sure it was loaded.  Below is a code snippet
I'm using these two packages for select 2 (showing the version numbers for clarity, but I'm not pinning those, just using the most recent)
natestrauser:select2@4.0.2
aldeed:autoform-select2@2.0.2


As a matter of note I don't let users add to this array.  I have something similar that does that, but I chose to use typeahead instead of select2 for that field, and I have a hook on the insert to check if what the user inputted was in the collection and if not, add it.

```
Titles:{
        type: [String],
        optional: true,
        autoform: {
            type: "select2",
            options: function () {
                if(titles_mapped.length === 0){
                    map_titles()
                }
                return titles_mapped
            },
            afFieldInput: {
                multiple: true,
                select2Options: {
                    // data:function () {
                    //     return titles_mapped
                    // },
                    tags: true
                }
            },
        }
    },
```

**Comment by alexandrzavalii** [comment]
@dpeet I am glad it's working!
Thanks for the snippet :)

**Comment by dpeet** [comment]
no problem, hope it helps out :D
