### ISSUE TITLE
Can not get existing value to be selected

### ISSUE THREAD

**Issue by pandabrand** [aldeed/meteor-autoform-select2#66]
I have looked everywhere and cant find an solution to this. I am pulling ids and values from one collection to be the options for my select. I'm not sure if that has anything to do with it. Select2 never uses it as selected, from the code you don't use first option. I don't know or if I can even set it. Am I missing something?

**Comment by isbjorn** [comment]
Did you use for a list of tags ```select2Options``` or ```options```?

This work for me (dumb solution with all data loaded at once):

```
{{> afQuickField name="allowedUserIds" type="select2" multiple=true options=usersToOptions }}
```

```javascript
function usersToOptions() {
  return Meteor.users.find(/* limits and sorting */).fetch().map((user) => {
      const text = userToText(user);

      return {
        label: text,
        value: user._id,
      };
    });
}

Template.myForm.helpers({
  usersToOptions
});

```

**Comment by nicolassalo** [comment]
I had a similar problem. I couldn't set the selected values. 
But I finally figured out why. The reason was, that the subscription for the options I was trying to set selected was not ready. So for everyone who has the same problem:
`$("select").select2();
Tracker.autorun(function() {
if (yourCollection.find().count() > 0) {
    $("selected").select2("val", selectedValue(s));
}
}`

**Comment by Sojourneer** [comment]
It seems that the recommend way to do this is to code some horrible looking custom dataAdapter.
Why is it sooooo incredibly hard for a simple maintain-field scenario!

**Comment by nicolassalo** [comment]
@Sojourneer 
Why don't you share your code snippet that's not working. Maybe I can help
